# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
    adapter: postgresql
    host: localhost
    port: 5432
    username: postgres
    password: 791126
    database: tzk3d_dev
    schema_search_path: public
    encoding: utf8
    template: template0



test:
    adapter: postgresql
    host: localhost
    port: 5432
    username: postgres
    password: 791126
    database: tzk3d_test
    schema_search_path: public
    encoding: utf8
    template: template0


production:
    adapter: postgresql
    host: localhost
    port: 5432
    username: postgres
    password: 791126
    database: tzk3d_production
    schema_search_path: public
    encoding: utf8
    template: template0

