# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: tzk3d_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 791126

test:
  adapter: postgresql
  encoding: unicode
  database: tzk3d_test
  pool: 5
  host: localhost
  port: 5432
  username: pgtest
  password: 791126



production:
  adapter: postgresql
  encoding: unicode
  database: tzk3d_production
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 791126



