# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: booking_girls_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: booking_girls_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: booking_girls_production
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres



