# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
    adapter: mysql2
    database: booking_girls_dev
    host: localhost
    port: 3306
    username: root
    password: "12345678"
    encoding: utf8

test:
    adapter: mysql2
    database: booking_girls_test
    host: localhost
    port: 3306
    username: root
    password: "12345678"
    encoding: utf8

production:
    adapter: mysql2
    database: booking_girls_production
    host: localhost
    port: 3306
    username: root
    password: 12345678"
    encoding: utf8




