# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: xiadan_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 791126

test:
  adapter: postgresql
  encoding: unicode
  database: xiadan_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 791126

production:
  adapter: postgresql
  encoding: unicode
  database: xiadan_production
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: 791126



