---
- !ruby/object:Technician
  attributes:
    id: 2
    name: '1111'
    age: 11
    price: 
    desc: '11'
    bwh: '11'
    state: pending
    created_at: 2013-08-01 12:42:45.393302000 Z
    updated_at: 2013-08-01 12:42:45.393302000 Z
    avatar: 
- !ruby/object:Technician
  attributes:
    id: 3
    name: '111'
    age: 11
    price: 
    desc: 
    bwh: 
    state: pending
    created_at: 2013-08-01 12:51:56.839455000 Z
    updated_at: 2013-08-01 12:51:56.839455000 Z
    avatar: 1111.jpg
- !ruby/object:Technician
  attributes:
    id: 4
    name: dsafasd
    age: 
    price: 
    desc: 
    bwh: 
    state: pending
    created_at: 2013-08-02 07:55:44.611787000 Z
    updated_at: 2013-08-02 07:55:44.611787000 Z
    avatar: 1111.jpg
